# Generated by Django 3.1.7 on 2021-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
